<a href="https://colab.research.google.com/github/bbell1988/tensorflow/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try yourself!



# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specifying the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

# Self-Practice

### Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [10]:
import tensorflow as tf

In [11]:
scalar = tf.constant(7)

print('ndim: ',scalar.ndim), print('size: ',tf.size(scalar).numpy())
scalar.shape

ndim:  0
size:  1


TensorShape([])

In [12]:
vector = tf.constant([4,3,2,1])

print('ndim: ',vector.ndim), print('size: ',tf.size(vector).numpy())
vector.shape

ndim:  1
size:  4


TensorShape([4])

In [13]:
matrix = tf.constant([[3,12,6,5],
                      [45,0,14,1]])

print('ndim: ',matrix.ndim), print('size: ',tf.size(matrix).numpy())
matrix.shape

ndim:  2
size:  8


TensorShape([2, 4])

I like to think of size as "how many elements are there in each set of brackets?" , or in each list.

Notice below that the outermost list has 2 elements, each their own lists that contain 3 elements themselves.

The next list contains 3 elements ( 3 individual lists)

And inside each list, there 5 elements

Therefore the size is (2,3,5)

In [14]:
tensor_235 = tf.constant([[[2,3,6,1,0],
                       [4,4,7,0,4],
                       [3,8,1,5,5]],
                      [[2,2,2,0,9],
                       [3,3,1,7,8],
                       [6,9,0,5,2]]])

print('ndim: ',tensor_235.ndim), print('size: ',tf.size(tensor_235).numpy())
tensor_235.shape

ndim:  3
size:  30


TensorShape([2, 3, 5])

In [15]:
tensor_233 = tf.constant([[[2,3,6],
                           [4,4,7],
                           [3,8,1]],
                          [[2,2,2],
                           [3,3,1],
                           [6,9,0]]])

print('ndim: ',tensor_233.ndim), print('size: ',tf.size(tensor_233).numpy())
tensor_233.shape

ndim:  3
size:  18


TensorShape([2, 3, 3])

In [16]:
tensor_1112 = tf.constant([[[[2,4]]]])

print('ndim: ',tensor_1112.ndim), print('size: ',tf.size(tensor_1112).numpy())
tensor_1112.shape

ndim:  4
size:  2


TensorShape([1, 1, 1, 2])

In [17]:
tensor_133 = tf.constant([[[2,3,6],
                           [4,4,7],
                           [3,8,1]]])

print('ndim: ',tensor_133.ndim), print('size: ',tf.size(tensor_133).numpy())
tensor_133.shape

ndim:  3
size:  9


TensorShape([1, 3, 3])

### Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [18]:
data1 = tf.random.uniform(shape=[5,300], seed=1) # documentation shows that unless specified, the values will be from [0,1)

In [19]:
data1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.2390374 , 0.92039955, 0.05051243, ..., 0.98160636, 0.9397274 ,
        0.9571533 ],
       [0.7466923 , 0.7157371 , 0.18135226, ..., 0.39082885, 0.88578534,
        0.17549968],
       [0.86248875, 0.7112448 , 0.83313787, ..., 0.54438615, 0.34139645,
        0.23390317],
       [0.26130998, 0.34569085, 0.06005359, ..., 0.72619724, 0.4790709 ,
        0.7699661 ],
       [0.47346985, 0.48816705, 0.7319356 , ..., 0.8416518 , 0.19057858,
        0.60791457]], dtype=float32)>

In [20]:
data2 = tf.random.uniform(shape=[5,300], seed=2)

In [21]:
data2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6787466 , 0.7141509 , 0.46981692, ..., 0.5545454 , 0.294469  ,
        0.83188725],
       [0.32239437, 0.42901587, 0.32162714, ..., 0.05301929, 0.87991524,
        0.9623717 ],
       [0.11586094, 0.65085936, 0.08858275, ..., 0.7520814 , 0.3141502 ,
        0.24934983],
       [0.548208  , 0.12416232, 0.16294503, ..., 0.94239736, 0.55103767,
        0.36462784],
       [0.38934302, 0.17725277, 0.71458256, ..., 0.94497836, 0.7527311 ,
        0.7274507 ]], dtype=float32)>

### Multiply the two tensors you created using matrix multiplication

In [22]:
mul_result = tf.matmul(a=data1,b=data2,transpose_b=True)

In [23]:
mul_result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.11711 , 80.06925 , 76.1739  , 81.06856 , 74.3251  ],
       [71.69417 , 79.91297 , 74.806145, 79.25944 , 76.904274],
       [72.95303 , 75.94667 , 75.53053 , 77.82711 , 79.27869 ],
       [72.15994 , 76.15966 , 73.88465 , 80.42831 , 77.3385  ],
       [74.01618 , 79.536575, 73.96097 , 79.74137 , 79.20613 ]],
      dtype=float32)>

### Multiply the two tensors you created in 3 using dot product

In [24]:
tf.tensordot(a=data1,b=tf.transpose(data2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.11712 , 80.06926 , 76.17389 , 81.06854 , 74.3251  ],
       [71.69416 , 79.91298 , 74.80615 , 79.25944 , 76.90428 ],
       [72.95304 , 75.946686, 75.53054 , 77.8271  , 79.27868 ],
       [72.15994 , 76.15965 , 73.884636, 80.42831 , 77.33849 ],
       [74.01618 , 79.53657 , 73.960976, 79.74137 , 79.20614 ]],
      dtype=float32)>

In [25]:
aa = tf.constant([[2,4],
                  [3,6]])

bb = tf.constant([[3,9],
                  [4,7]])

In [26]:
tf.tensordot(a=aa,b=bb,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 46],
       [33, 69]], dtype=int32)>

The above does matrix multiplication as expected

In [31]:
tf.tensordot(a=aa,b=bb,axes=0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 6, 18],
         [ 8, 14]],

        [[12, 36],
         [16, 28]]],


       [[[ 9, 27],
         [12, 21]],

        [[18, 54],
         [24, 42]]]], dtype=int32)>

### Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [35]:
tensor_shape224 = tf.random.uniform(shape=[224,224,3])

### Find the min and max values of the tensor you created in 6.

In [37]:
tf.reduce_min(tensor_shape224)

<tf.Tensor: shape=(), dtype=float32, numpy=5.722046e-06>

In [38]:
tf.reduce_max(tensor_shape224)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999956>

### Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [42]:
squeezable = tf.random.uniform(shape=[1,224,224,3])
squeezable

tf.squeeze(squeezable)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.12415695, 0.33751965, 0.32126164],
        [0.2943288 , 0.8360143 , 0.55043316],
        [0.21018314, 0.8741846 , 0.71938705],
        ...,
        [0.6004274 , 0.07333398, 0.33687186],
        [0.8821511 , 0.9742578 , 0.37916195],
        [0.8115698 , 0.6433327 , 0.21358383]],

       [[0.81634164, 0.93622303, 0.15603566],
        [0.8759779 , 0.781427  , 0.27019548],
        [0.7776177 , 0.8436508 , 0.2440213 ],
        ...,
        [0.11293745, 0.7486737 , 0.15767682],
        [0.49452436, 0.6453936 , 0.53716135],
        [0.39884055, 0.6938803 , 0.11455369]],

       [[0.9499124 , 0.11225152, 0.24740183],
        [0.1650387 , 0.3245728 , 0.02028024],
        [0.1160233 , 0.01129901, 0.13162863],
        ...,
        [0.4997449 , 0.80436766, 0.44451356],
        [0.06865835, 0.47786808, 0.05597913],
        [0.34036255, 0.81753683, 0.3937316 ]],

       ...,

       [[0.8629509 , 0.41195464, 0.936713  ],
        [0.72

### Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [43]:
shape10_tensor = tf.constant([10, 4, 13, 20, 5, 14, 1, 1, 0, 6])

In [44]:
shape10_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([10,  4, 13, 20,  5, 14,  1,  1,  0,  6], dtype=int32)>

In [46]:
tf.one_hot(indices=shape10_tensor,depth=3)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

depth gives how determines how high of values can be shown.
For example:

Depth = 3 [0,0,0]
Depth = 5 [0,0,0,0,0]

Depth is essentially the amount of columns we will see

The indices are the numbers to one-hot encode. So in this case, there will be 10 rows total

For the sake of this problem, since the highest number in the indices is 20, we will need a depth of 21 in order to capture all of the values. See below!

In [48]:
tf.one_hot(indices=shape10_tensor,depth=21)

<tf.Tensor: shape=(10, 21), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0