<a href="https://colab.research.google.com/github/bbell1988/tensorflow/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try yourself!



# Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector
vector.ndim

1

In [ ]:
# create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specifying the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

# Self-Practice

### Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
import tensorflow as tf

In [85]:
scalar = tf.constant(7)

print('ndim: ',scalar.ndim), print('size: ',tf.size(scalar).numpy())
scalar.shape

ndim:  0
size:  1


TensorShape([])

In [84]:
vector = tf.constant([4,3,2,1])

print('ndim: ',vector.ndim), print('size: ',tf.size(vector).numpy())
vector.shape

ndim:  1
size:  4


TensorShape([4])

In [83]:
matrix = tf.constant([[3,12,6,5],
                      [45,0,14,1]])

print('ndim: ',matrix.ndim), print('size: ',tf.size(matrix).numpy())
matrix.shape

ndim:  2
size:  8


TensorShape([2, 4])

I like to think of size as "how many elements are there in each set of brackets?" , or in each list.

Notice below that the outermost list has 2 elements, each their own lists that contain 3 elements themselves.

The next list contains 3 elements ( 3 individual lists)

And inside each list, there 5 elements

Therefore the size is (2,3,5)

In [82]:
tensor_235 = tf.constant([[[2,3,6,1,0],
                       [4,4,7,0,4],
                       [3,8,1,5,5]],
                      [[2,2,2,0,9],
                       [3,3,1,7,8],
                       [6,9,0,5,2]]])

print('ndim: ',tensor_235.ndim), print('size: ',tf.size(tensor_235).numpy())
tensor_235.shape

ndim:  3
size:  30


TensorShape([2, 3, 5])

In [80]:
tensor_233 = tf.constant([[[2,3,6],
                           [4,4,7],
                           [3,8,1]],
                          [[2,2,2],
                           [3,3,1],
                           [6,9,0]]])

print('ndim: ',tensor_233.ndim), print('size: ',tf.size(tensor_233).numpy())
tensor_233.shape

ndim:  3
size:  18


TensorShape([2, 3, 3])

In [81]:
tensor_1112 = tf.constant([[[[2,4]]]])

print('ndim: ',tensor_1112.ndim), print('size: ',tf.size(tensor_1112).numpy())
tensor_1112.shape

ndim:  4
size:  2


TensorShape([1, 1, 1, 2])

In [79]:
tensor_133 = tf.constant([[[2,3,6],
                           [4,4,7],
                           [3,8,1]]])

print('ndim: ',tensor_133.ndim), print('size: ',tf.size(tensor_133).numpy())
tensor_133.shape

ndim:  3
size:  9


TensorShape([1, 3, 3])

### Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [89]:
data1 = tf.random.uniform(shape=[5,300], seed=1) # documentation shows that unless specified, the values will be from [0,1)

In [90]:
data1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.3875184 , 0.7485455 , 0.54871905, ..., 0.43299985, 0.21701062,
        0.8580793 ],
       [0.29721284, 0.07816195, 0.07263577, ..., 0.97732425, 0.740196  ,
        0.40200448],
       [0.99352324, 0.7668098 , 0.13661015, ..., 0.6491897 , 0.03674686,
        0.35594702],
       [0.5936897 , 0.8116046 , 0.59611714, ..., 0.84157944, 0.8777541 ,
        0.9207442 ],
       [0.16323543, 0.5122404 , 0.5867741 , ..., 0.38197076, 0.9409027 ,
        0.70660126]], dtype=float32)>

In [91]:
data2 = tf.random.uniform(shape=[5,300], seed=2)

In [92]:
data2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.01476038, 0.3965603 , 0.64154613, ..., 0.3521223 , 0.50791466,
        0.9924396 ],
       [0.15385628, 0.73710203, 0.03105795, ..., 0.19707048, 0.12957   ,
        0.07000494],
       [0.10715544, 0.42963457, 0.95503855, ..., 0.9423845 , 0.42851102,
        0.37013483],
       [0.5849999 , 0.3084643 , 0.6610925 , ..., 0.31700587, 0.17780745,
        0.68700004],
       [0.5284779 , 0.67358804, 0.8820958 , ..., 0.6116805 , 0.8348483 ,
        0.77032745]], dtype=float32)>

### Multiply the two tensors you created using matrix multiplication

In [94]:
mul_result = tf.matmul(a=data1,b=data2,transpose_b=True)

In [95]:
mul_result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.31407 , 75.357414, 76.69586 , 78.49614 , 80.84558 ],
       [73.1833  , 76.0802  , 74.51737 , 78.80843 , 83.85922 ],
       [74.51157 , 77.26175 , 76.27721 , 78.03581 , 82.114456],
       [72.221344, 72.85527 , 73.20939 , 74.03663 , 78.22226 ],
       [71.40582 , 71.79626 , 71.429245, 75.54306 , 75.85847 ]],
      dtype=float32)>

### Multiply the two tensors you created in 3 using dot product

In [99]:
aa = tf.constant([[2,4],
                  [3,6]])

bb = tf.constant([[3,9],
                  [4,7]])

In [101]:
tf.tensordot(a=aa,b=bb,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 46],
       [33, 69]], dtype=int32)>

In [98]:
tf.tensordot(a=data1,b=data2,axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[5.71991690e-03, 1.53674424e-01, 2.48610929e-01, ...,
          1.36453882e-01, 1.96826279e-01, 3.84588629e-01],
         [5.96221387e-02, 2.85640597e-01, 1.20355291e-02, ...,
          7.63684362e-02, 5.02107628e-02, 2.71282028e-02],
         [4.15247045e-02, 1.66491300e-01, 3.70095015e-01, ...,
          3.65191340e-01, 1.66055903e-01, 1.43434063e-01],
         [2.26698235e-01, 1.19535588e-01, 2.56185532e-01, ...,
          1.22845612e-01, 6.89036623e-02, 2.66225159e-01],
         [2.04794914e-01, 2.61027753e-01, 3.41828376e-01, ...,
          2.37037450e-01, 3.23519081e-01, 2.98516065e-01]],

        [[1.10488124e-02, 2.96843439e-01, 4.80226487e-01, ...,
          2.63579577e-01, 3.80197257e-01, 7.42886245e-01],
         [1.15168430e-01, 5.51754415e-01, 2.32482925e-02, ...,
          1.47516221e-01, 9.69890505e-02, 5.24018854e-02],
         [8.02107304e-02, 3.21601033e-01, 7.14889824e-01, ...,
          7.05417693e-0